### PR TITLE
nuke: Fix txReader to properly restore saved mip level knob value

### PR DESCRIPTION
**Pull request by nrusch**
## Description

Proposed fix for https://github.com/OpenImageIO/oiio/issues/1455.

The issue is caused by the fact that the user-facing `Enumeration_knob` is populated from within the Reader's constructor, which is too late when the Read is created with a non-default mip level (e.g. when loading a saved script).

To work around this without resorting to saving all of the knob's menu items, the menu index is no longer stored by the Read or used in the op hash. Instead, its value is copied to a hidden `Int_knob`, which drives the actual Reader and gets saved when the Read is serialized.

Also, the txReader now sets the bit-depth metadata key properly when the input file contains `half` data, which was an earlier oversight.

### CODE REVIEW

**Comment by dbr** [comment]
Seems good to me - thanks!

**Comment by lgritz** [comment]
fixes #1455 
(I think you have to say it like that)

**Comment by lgritz** [comment]
LGTM. I'll test it on my end and if it builds properly, I'll merge it into master and RB-1.7.

**Comment by lgritz** [comment]
Builds for me. Merging.

**Pull request merged**
