### PR TITLE
Docs: Make sure README has links for slack and meetings

### PR DESCRIPTION
**Pull request by lgritz**

### CODE REVIEW

**Review by ThiagoIze — APPROVED** [review]
Looks good and I verified the links work.

**Comment by kikaxa** [comment]
why is the last commit appeared in https://github.com/AcademySoftwareFoundation/OpenImageIO/commits/v2.4.14.0 release branch?
 it broke source hash check, e.g. in vcpkg

**Comment by lgritz** [comment]
@kikaxa I don't understand, why would it be a problem to backport this README change to a release?

**Comment by kikaxa** [comment]
I am sorry, it isnt really. This commit happened before the breakage but at a similar time. 
After further investigating we found the source hash change was caused by this repo migration, not the commit

**Pull request merged**
