### PR TITLE
Build: enable parallel compilation when using visual studio

### PR DESCRIPTION
**Pull request by aras-p**
## Description

Cmake-generated visual studio project files were using just one CPU core for all the compilation, which is not terribly fast. Add the `/MP` option so that it compiles separate .cpp files in parallel. On my (16 core, 32 thread) machine this makes a Release build of OpenImageIO.lib go from 136 sec down to 30 sec.

## Tests

N/A

## Checklist:

- [x] I have read the [contribution guidelines](https://github.com/OpenImageIO/oiio/blob/master/CONTRIBUTING.md).
- [ ] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](https://github.com/OpenImageIO/oiio/blob/master/src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](https://github.com/OpenImageIO/oiio/blob/master/src/doc/CLA-CORPORATE)).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
Wow, I had no idea this was necessary. CMake seems pretty good about automatically using parallel builds (at least when CMAKE_BUILD_PARALLEL_LEVEL is set) for make or ninja. I just assumed it would do the right thing for MSVS as well.

Or... are you saying that this is forcing a parallel build because you don't use or don't know about CMAKE_BUILD_PARALLEL_LEVEL? Is there any downside to forcing it and not having a way for users to turn it off?

**Comment by aras-p** [comment]
`CMAKE_BUILD_PARALLEL_LEVEL` seems to only affect the case when "make itself" does the build. When you generate a visual studio project and from the VS IDE, then all the build gets done through visual studio's MSBuild system. And that one needs `/MP` specified in the compiler settings to compile multiple .cpp files in parallel in the same project. It will still try to build multiple _projects_ in parallel by default (when they don't depend on each other), but in OIIO case there isn't all that many to begin with.

I just checked with passing `CMAKE_BUILD_PARALLEL_LEVEL` either as an env. var or a cmake option, and neither affects the visual studio project build throughput.

**Comment by lgritz** [comment]
Oh, I see, that makes sense -- for make/ninja as well, it only affects the "cmake --build" step, not the configure step.

**Review by lgritz — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
