### PR TITLE
Convert dpx output to be ioproxy enabled

### PR DESCRIPTION
**Pull request by kdt3rd**
Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>

## Description

Converts dpx output (input is already) to use the IO proxy layer (I recently
had a reason to write dpx, but couldn't make a memory stream).

## Tests

just tested with dpx image tests

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [x] I have updated the documentation, if applicable.
- [x] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
Did you clang-format OutStream.h by hand? We had excluded it from "make clang-format" because it's imported from another project and we wanted to retain the ability to easily diff between them. I'm tempted to recommend reverting the format-only changes to existing code.

**Comment by lgritz** [comment]
But I'm not really going to get bent out of shape about it. In truth, it has been extremely rare over the years for us to need to diff these files versus the originals. And with IOProxy, the files really do have differences, whereas they used to be identical.

**Comment by lgritz** [comment]
Looks like CI is failing the "imageinout_test", which (among other things) for all file types supporting proxies, will write a file and write a proxy and then verify that they are byte for byte identical.

**Comment by kdt3rd** [comment]
I did reformat the outstream when I did the pull request because I looked at the code after the comment in the PR template - and it wasn't following the same style, so I thought it just hadn't been visited in a while to have been formatted. Happy to revert that if you'd prefer.

I ran ctest (i.e. ninja -C <buildfolder> test) and that succeeded for me, I wonder what I'm missing that imageinout_test doesn't run...

**Comment by lgritz** [comment]
Try running by hand, it lives in `BUILDAREA/bin/imageinout_test`

**Comment by lgritz** [comment]
I mildly prefer that you remove the formatting change, but only if it's super easy. It's not worth the hassle of extra work, I'm just being superstitious about wanting "imported" source to restict diffs versus upstream to only the things we purposely change.

**Comment by kdt3rd** [comment]
ah, I forgot dpx puts the filename in the header. I've changed the test  write proxy to just use the disk filename, do you know of any issues with that? I believe I reverted the change to formatting OutputStream.cpp

**Comment by lgritz** [comment]
That sounds reasonable. In the imageinout_test we are also careful to set the DateTime attribute to something fixed so that files don't differ because of that metadata.

**Comment by lgritz** [comment]
Would you mind also fixing builtinplugins.rst to note that DPX takes proxies for output as well as input now?

**Review by lgritz — APPROVED** [review]
LGTM.

**Pull request merged**
