### PR TITLE
Adding IOProxy support to ICOInput

### PR DESCRIPTION
**Pull request by jasonbaumeister**
## Description

This updates ICOInput to use the IOProxy model so it can read from files or the IOMemReader

## Tests

The current ICO tests still pass exercising the new code. I didn't see anything in the other formats with IOProxy support to explicitly test the in memory options

## Checklist:

- [x] I have read the [contribution guidelines](https://github.com/OpenImageIO/oiio/blob/master/CONTRIBUTING.md).
- [ ] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](https://github.com/OpenImageIO/oiio/blob/master/src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](https://github.com/OpenImageIO/oiio/blob/master/src/doc/CLA-CORPORATE)).
- [ ] I have updated the documentation, if applicable.
- [x] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
Can you please add the DCO sign-off to your patch? (`git commit --amend -s`, then re-push ought to do it)

**Comment by jasonbaumeister** [comment]
> Can you please add the DCO sign-off to your patch? (`git commit --amend -s`, then re-push ought to do it)

Done.

**Comment by lgritz** [comment]
Sorry, it needs to be on each commit. You can squash them all down and then make sure it's on the one, or you can edit each commit message to have the "Signed-off-by: " field.

**Comment by jasonbaumeister** [comment]
> Sorry, it needs to be on each commit. You can squash them all down and then make sure it's on the one, or you can edit each commit message to have the "Signed-off-by: " field.

Sorry about that, should all be fixed now.

**Review by lgritz — APPROVED** [review]
LGTM, thanks for these fixes!

I took the liberty of pushing an additional change that adds the docs for this. After it passes CI on that, I'll merge it.

**Review by lgritz — CHANGES_REQUESTED** [review]
Wait, I just realized, you forgot something -- both ICOInput and ICOOutput need implementations of `supports()` that will respond correctly to a query about IOProxy. Look in, say, dpxinput.cpp for an example.

**Comment by lgritz** [comment]
As for your comment about testing -- the existing imageinout_test will try IOProxy and MemReader for every format that says it supports IOProxy.  (In fact, starting to type this reply to you is how I remembered to check that you had done that, and saw that you didn't! Once you declare that it supports IOProxy, the test should catch anything you've done wrong in the implementation.)

**Comment by jasonbaumeister** [comment]
supports() should be implemented for ICOInput now.

I took a quick look at supporting IOProxy for ICOOutput as well and it looks like the only real catch is that it needs to be able to open a file in 'r+b' instead of 'wb' that ImageOutput::ioproxy_use_or_open() always uses.

I can add a new value to the Filesystem::IOProxy::Mode enum for ReadWrite and add a mode param to ImageOutput::ioproxy_use_or_open, defaulted to Filesystem::IOProxy::Mode::Write and have that working, if that sounds like the correct approach to you.

**Comment by lgritz** [comment]
How about this: Let's merge the ICO input proxy support on its own, and tackle the output proxy separately. We need to take a hard look at whether append is really needed here or it's just a quirk of the implementation from 13 years ago (supporting evidence: I don't think any of the other format writers did this), or if is truly needed, make sure that the operation we do on IOProxy is not introducing any bugs or weird semantics.

**Comment by lgritz** [comment]
Uh oh, it looks like now that you marked it as supports("ioproxy"), the imageinout_test is failing.

**Comment by jasonbaumeister** [comment]
imageinout_test is passing now. I took a closer look at how BMPInput worked and the ioseek(0) before the first read was required.

**Review by lgritz — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
