### PR TITLE
OCIO improvements

### PR DESCRIPTION
**Pull request by Shootfast**
## Description

Added Role accessors to ColorConfig class.
Added OpenColorIO_STATIC define (needed to pass Windows dllimport definitions)

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by Shootfast** [comment]
I don't neeed it per-se, but it would be awesome if you could!

**Comment by lgritz** [comment]
Just adding a few non-virtual functions should be totally safe, I'll backport it.

**Comment by Shootfast** [comment]
Ah sure thing

**Comment by lgritz** [comment]
Looks good. Merging.

**Pull request merged**
