### PR TITLE
Fix error reading tiles for mixed-format exr files.

### LINKED ISSUE #1335: 1.6.x fails to read correctly mixed bit depth EXR file
1.5.23 reads correctly the following file https://github.com/MrKepzie/build-oiio/blob/master/chopper.exr 
with oiiotool:

`oiiotool chopper.exr -o chopper_o.exr `

But seems to be broken in 1.6.9: the output file for the RGBA pass only has the red channel set and other passes are blanked

### PR DESCRIPTION
**Pull request by lgritz**
Fixes #1335

### CODE REVIEW

**Comment by MrKepzie** [comment]
This correctly fixes the issue

**Comment by lgritz** [comment]
I also backported to RB-1.6.

**Comment by MrKepzie** [comment]
We'll probably move soon to RB-1.6 then. We have several patch also to validate against 1.6 (mostly related to MingW support)

**Comment by lgritz** [comment]
Great. As they come through one by one, I will merge them into 1.6. Let me know when we have tackled them all, and then I'll tag a release at that point.

**Pull request merged**
