### PR TITLE
API: Add shutdown method

### PR DESCRIPTION
**Pull request by LazyDodo**
## Description

This change adds a `shutdown` method to the API that can be used to perform shutdown of the thread-pool(s) (or other clean-up activities). Applications that utilize OpenImageIO must call it before exiting their main function to prevent possible deadlocks during application shutdown (see #3851)

This change also updates the documentation and all oiio-tools to call the new `shutdown` method.

This is the final change for fixing #3851

## Tests

No tests added / unsure how to test for it.

## Checklist:

- [x] I have read the [contribution guidelines](https://github.com/OpenImageIO/oiio/blob/master/CONTRIBUTING.md).
- [x] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](https://github.com/OpenImageIO/oiio/blob/master/src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](https://github.com/OpenImageIO/oiio/blob/master/src/doc/CLA-CORPORATE)). - Minimal change, no CLA required
- [x] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by LazyDodo** [comment]
An update to #3805 to make it not use `atexit` is still forthcoming but not required to mark #3851 as fixed, hence not included.

**Review by lgritz — CHANGES_REQUESTED** [review]
Code LGTM, but let's move the docs to the existing API chapter as I noted inline.

**Comment by lgritz** [comment]
Should we do anything about Python? Expose OIIO::shutdown() through the python bindings? Or should we ensure that when python module unloads, it will call shutdown?

Is there harm in calling shutdown twice()? In calling anything that uses the thread pool after shutdown()? (Does it automatically set it up again?) 

What are the instructions we should give to a library author who uses OIIO and isn't sure if, at runtime, the app itself uses OIIO, or knows the library uses OIIO, so the app would call shutdown? Or what if the app uses other libraries that use OIIO but each one isn't sure if they are the only one?

**Comment by LazyDodo** [comment]
I'll have to admit : not a python guy. 

If i had to guess I'm guessing when python shuts down it unloads all modules before existing causing the regular dtor for the threadpool to run long before the process exists so all threads still be alive? so likely not a problem? But I admit wildly guessing here, would have to check with the debugger or sprinkle some printf's to validate this theory.

**Comment by lgritz** [comment]
Oh, yes, you're probably right. I guess this is only a problem when the process ends naturally but terminates so quickly that the threads are killed before the pool has finished releasing?

Let's move forward on this and we can always amend later if there's another edge case we haven't considered.

**Review by lgritz — APPROVED** [review]
LGTM

**Pull request merged**
