### PR TITLE
clean up spelling in image{buf,io}.h

### PR DESCRIPTION
**Pull request by dankamongmen**
## Description

Correct some spelling issues in these two headers. One change I did **not** make was
`make_writeable()` -> `make_writable()`, for obvious reasons.

## Tests

It still compiles.

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [ ] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by dankamongmen** [comment]
Individual CLA was mailed out this morning.

**Comment by lgritz** [comment]
I checked several dictionaries, and they are about evenly split about whether "writeable" is an alternate spelling of "writable" or if they don't mention the former at all. Some google searching indicates it's at least very widely used in software APIs. So either lots of API designers and docs writers have the same habitual misspelling, or it's perfectly fine. A full grep through the codebase seems to indicate that I have used both, though writeable more commonly. I'm on the fence about whether to fix in the function names.

**Comment by lgritz** [comment]
See #2567 for some more writeable renaming

**Comment by dankamongmen** [comment]
Awesome, thanks for the merge. I wasn't going to push on writable, but I think you made the right call :).

**Pull request merged**
