### PR TITLE
Fix error decoding Apple HEIF files

### LINKED ISSUE #2794: [BUG] Unable to open Apple HEIC images
**Describe the bug**
With OpenImageIO compiled with libheif 1.9.1 I am able to open HEIC/HEIF images. However, Apple HEIC files from various iPhones and iPads do not load.

**To Reproduce**
1. Build OIIO with libheif
2. Call `ImageInput::open` with one of the examples below
3. ImageInput will throw an unknown exception

**Expected behavior**
I expect it to handle the HEIC files like other non-Apple HEIC files. For non-Apple samples, I've used files from [this repository](https://github.com/tigranbs/test-heic-images) which do load correctly.

**Evidence**
The images that cause these errors come from iPhones and iPads. I've attached one of each [here](https://github.com/OpenImageIO/oiio/files/5736369/Examples.zip).

One thing I've noticed is that non-loading HEIC files have an additional brand `MiPr`, which according to my searching is for "Multi-Image Application format brand for progressive decoding and rendering". Maybe this is not supported?

For reference, the code throwing the error is this:
```cpp
OIIO::ImageInput::unique_ptr in_p = nullptr;
OIIO::ImageSpec config;
setupRawSpec(config);  // This is a series of config.attribute calls to set stuff like "raw:use_camera_wb", etc

try {
    in_p = OIIO::ImageInput::open(fileName.toStdString(), &config);
} catch (std::exception& ex) {
    qCritical() << "ImageInput::open Exception:" << ex.what();
    // ...
} catch (...) {
    qCritical() << "ImageInput::open Unknown Exception";  // This is what gets hit when opening Apple HEIC files
    // ...
}
```

**Platform information:**
 - OIIO branch/version: 2.2.9.0
 - OS: Windows and Mac
 - C++ compiler: MSVC 2019 on Windows, XCode 12.1 on Mac
 - Any non-default build flags when you build OIIO: `USE_LIBHEIF=1` and `USE_LIBRAW=1` I believe are the only non-defaults.

### PR DESCRIPTION
**Pull request by hjmallon**
## Description

* 0 size metadata causes an issue in the libheif cxx wrapper
* fixes #2794

## Tests

I have tested with the samples from #2794 

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

Upstream fix: https://github.com/strukturag/libheif/pull/415

### CODE REVIEW

**Review by lgritz — COMMENTED** [review]
LGTM! I will merge when the CI tests finish (assuming they don't turn up anything unexpected).

**Review by lgritz — APPROVED** [review]

**Comment by lgritz** [comment]
What leads to this 0 byte metadata? Is there any metadata expected to have 0 size, or is that an oddity of the file itself?

**Comment by hjmallon** [comment]
> What leads to this 0 byte metadata? Is there any metadata expected to have 0 size, or is that an oddity of the file itself?

I honestly have no idea. The example code in libheif checks for 0 size before copying the data so works fine, but that check isn't in the cxx bindings. Maybe the original issue creator @AdamMainsTL could say?

**Comment by AdamMainsTL** [comment]
Thank you very much for the quick fix! I'll try to update soon.

For the images as far as I'm aware they were just taken straight from an iPhone (12 pro max), another iPhone (non-12) that I didn't upload, and one from an iPad. I'm asking the person who took them all whether they have some privacy setting or something that would cause this as I didn't strip anything on my end. The entire chain of custody for the images would have been Apple device -> Slack -> attempt to load, so it's also possible Slack removed data.

**Comment by AdamMainsTL** [comment]
Got an update. The full chain was actually iPhone -> Airdrop to Mac -> Slack. It seems like Airdrop is the weak link according to this thread: https://discussions.apple.com/thread/251040579

**Comment by lgritz** [comment]
Interesting, thanks for the investigation.

**Pull request merged**
