### PR TITLE
Gcc 7 1 0 / Qt 5.8 fixes

### PR DESCRIPTION
**Pull request by Shootfast**
## Description

The following are small fixes caught by the GCC 7.1.0 compiler when used in combination with Qt 5.8.
As it stands there are still a number of warnings being emitted, but their scope was much greater than my drive-by edit had time to fix.

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
LGTM. As soon as I try it at work to make sure nothing breaks there, I will merge it.

**Comment by Shootfast** [comment]
There are actually a whole bunch more compiler warnings from GCC 7.1.0, though I'm not able to address them all at the moment.

**Comment by lgritz** [comment]
Do you mean you don't have time to address them, or you don't know HOW to address them? If the latter, feel free to just post the error messages, and I may be able to make a good guess about how to fix the warnings.

In the mean time, I'll see if I can set up Travis to add a gcc7 compile to the mix, that'll get things cleared up fast.

**Comment by lgritz** [comment]
These changes seem fine both on my laptop and work machine, so I will merge now. Thanks for the fixes!

**Pull request merged**
