### PR TITLE
raw: unpack the pixels when you need them, not when you open

### PR DESCRIPTION
**Pull request by lgritz**
I'm concerned about this breaking raw reads. Looks ok to me and works on my cursory tests, but other stakeholders that rely on the raw format reader should please try this patch on their end and let me know if it's ok!

### CODE REVIEW

**Comment by lgritz** [comment]
I got an email confirmation from the user who suggested this fix, indicating that it works.

I'd love to also hear from @danwexler that this for sure doesn't break his stuff.

**Comment by lgritz** [comment]
Merged

**Comment by akihiroy** [comment]
The vertical raw picture is broken after this commit.

**Comment by lgritz** [comment]
@akihiroy Can you point me to (or send me) an email that exhibits this problem?

**Comment by akihiroy** [comment]
@lgritz The picture width and height looks horizontal orientation, but the actual pixel data looks vertical orientation.
You can reproduce by the last raw file (sony_a3000_20.arw) in http://www.photographyblog.com/reviews/sony_a3000_review/sample_images/

**Comment by lgritz** [comment]
Sorry for the breakage. I think that #1863 will address the problem.

**Pull request merged**
