### PR TITLE
IBA::contrast_remap() and oiiotool --contrast

### PR DESCRIPTION
**Pull request by lgritz**
Allows flexible linear or sigmoidal contrast remapping.

### CODE REVIEW

**Comment by lgritz** [comment]
@marsupial Any opinions?

**Comment by marsupial** [comment]
Yet to try it out, but liking the curves/ramp and per-channels.
Still into the idea of getting max/min and fitting a range in one call, but maybe the use-case is too specialized, easily added, or I'm reading the docs wrong?

**Comment by lgritz** [comment]
Does it have to be in one call (C++/Python)? Or can it just be super easy on one oiiotool command line? Because the latter is straightforward, I just wanted to do that as a separate PR.

**Comment by marsupial** [comment]
Agree its a separate topic and can be dealt with after.
Think/prefer it would be programmatic though rather than `oiiotool`.
I can just rebase & tinker with #2035, and if you think it's too specific, just use it from the client

**Pull request merged**
