### PR TITLE
Prevent a doubled-up error message in get_image_info

### PR DESCRIPTION
**Pull request by fpsunflower**
Prevent error messages from getting doubled-up in get_image_info if a handle is created during the call

Minor optimization to how errors are cleared in exists queries

### CODE REVIEW

**Comment by lgritz** [comment]
LGTM

**Comment by fpsunflower** [comment]
Merged.

**Comment by lgritz** [comment]
I think you merged a version that fails the clang-format test.

**Comment by lgritz** [comment]
Don't worry, I'll fix it.

**Pull request closed without merging**
