### PR TITLE
Updates after API simplification pass in EXR master

### PR DESCRIPTION
**Pull request by kdt3rd**
## Description

The core API has been made consistent with the language in the file
layout documentation. This is an update after that lands

Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [x] I have updated the documentation, if applicable.
- [x] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Review by lgritz — APPROVED** [review]

**Comment by lgritz** [comment]
I'll wait until you merge the openexr side before merging this one.

**Comment by kdt3rd** [comment]
This should be landed now. I will have changed the output in cleaning up a few messages, but I don't know what you did in terms of those reference prints and testing the corrupt files

**Comment by lgritz** [comment]
I updated the reference output for you. Will merge when the CI finishes to verify that I got it right.

**Comment by lgritz** [comment]
Do I understand correctly that this code currently does not work with DWA compressed files?

**Pull request merged**
