### PR TITLE
Adding basic TextureSystem support for python.

### PR DESCRIPTION
**Pull request by alister-chowdhury**
This PR contains some basic TextureSystem python bindings (#2828).

I haven't added any support for `PerThread`, `TextureHandle` or `TextureBatchOpt` function overloads.
Nor have I added `shadow`, since it appears to just be a dummy that returns `false`?
Additionally I haven't added a way to provide a `ImageCache` to the `TextureSystem`, mainly due to the way wrapping around `create` and `destroy` works, which sounds like opening a can of worms in regards to pointer management.

I couldn't quite figure out the most appropriate way to setup tests for these, I was more-or-less hoping to copy C++ tests for the `TextureSystem`, but was unable to find anything that looked like a good starting point?

### CODE REVIEW

**Review by lgritz — COMMENTED** [review]
This looks great, thanks!

**Review by lgritz — CHANGES_REQUESTED** [review]
To complete this PR, would you mind adding a test to the testsuite, akin to the other python-* tests, just to have a way to verify that the basic functionality works? I don't think it needs to do much other than create a TS, do a couple lookups from a known small texture and verify the results. But just to have some sanity check that the basics must be working and callable from Python.

**Comment by lgritz** [comment]
I don't think you should bother with the PerThread, handles, or the batched stuff.  Let's start with the basics, it's not clear that anybody using this from Python will need any of those. This looks great except for lack of test. Look at a few of the testsuite/python-* tests to see how I did it for the other python classes, it's fairly straightforward.

**Comment by alister-chowdhury** [comment]
Hrm...
`Linux oldest/hobbled: gcc4.8/C++11 py2.7 boost-1.66 exr-2.2 no-sse no-ocio`, `Linux static libs: gcc7 C++14 exr2.4` and `Linux 2017-ish: gcc4.8/C++11 py2.7 boost-1.66 exr-2.3` are falling over due to a segfault...

I'm not sure what the best way to debug this (since I don't have a setup which matches these enviroments).
Is there a way of extracting out the segfault from the tests?

**Comment by lgritz** [comment]
Sorry for the delay. I'll try on my end and see if I can reproduce the failure.

**Comment by lgritz** [comment]
I was able to reproduce this crash (I think only with combination of python 2.7 and somewhat older pybind11). Testing a fix now. If it works, I'll try to amend your PR by pushing the fix to your branch.

**Comment by lgritz** [comment]
I pushed fixes to your branch.

The fix to the crashes was some minor rearrangement of how we release the GIL. Some combination of python2.7 and older pybind11 was not liking our constructing the result tuple of the texture call inside the block where we had gil_scoped_release.

I also changed some `TextureOptWrap*` to `TextureOptWrap&`.

And a couple minor renames, for example testsuite/python-texture-sys to testsuite/python-texturesys, to stick to the prevailing convention of using the class name.

If CI tests pass, I'll merge. I'm expecting a couple to fail for unreleated reasons -- your changes were based off a master of a few weeks ago, and I subsequently fixed some totally unrelated CI breaks.

**Review by lgritz — APPROVED** [review]
Looks good pending completion of CI tests.

**Comment by alister-chowdhury** [comment]
Oh I see, I wouldn't have though the release gil needed to be scoped!
Thanks Larry!

**Pull request merged**
