### PR TITLE
Fix Windows warnings

### LINKED ISSUE #2246: RB-2.2 - Compilation warning fixes - VS2017 & VS2015
Here are three patches to fix some warnings with **VS2017** (and VS2015) and the branch **RB-2.2**. 

When compiling OIIO I did not see them. But these warnings were present when compiling OCIO with VS2017 & VS2015. So I built these patches to avoid disabling some compiler flags in the OCIO project. They all seem to be easy fixes but some could highlight precision concerns (i.e. simd.h). So, please carefully review them before changing the OIIO code.

[fmath_h_patch.txt](https://github.com/OpenImageIO/oiio/files/3242257/fmath_h_patch.txt)
[simd_h_patch.txt](https://github.com/OpenImageIO/oiio/files/3242134/simd_h_patch.txt)
[ustring_h_patch.txt](https://github.com/OpenImageIO/oiio/files/3242135/ustring_h_patch.txt)

### PR DESCRIPTION
**Pull request by lgritz**
Submitted on behalf of Patrick Hodoul, with some minor mods by LG.

Fixes #2246

### CODE REVIEW

**Comment by lgritz** [comment]
Note that the stof is just plain an error, not merely fixing a warning.

**Comment by fpsunflower** [comment]
LGTM!

Maybe we should look into `-Wconversion` (or similar) to try and match the sensitivity for these types of errors on the gcc/clang side?

**Comment by hodoulp** [comment]
Sorry to hick-jack your discussion but I tried the flag `-Wconversion` on OCIO and it detects good warnings.

**Comment by lgritz** [comment]
Updated to minimize the diffs, eliminated the unnecessary `const`

**Pull request merged**
