### PR TITLE
Fix building on OpenBSD

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Review by lgritz — CHANGES_REQUESTED** [review]
Thanks for the fix!

LGTM, though it seems to be failing the "clang-format" test, can you please fix the line wrap here? (Click on the failed test to see where it "breaks," which will include the diff that shows how to make it conform.)

**Comment by brad0** [comment]
> though it seems to be failing the "clang-format" test

Sure thing, done.

**Review by lgritz — APPROVED** [review]
LGTM, thanks. Will merge as soon as the rest of the CI passes.

**Comment by lgritz** [comment]
Oops, I thought the "merge queue" would wait until all the checks passed. Oh well. I think it's safe, I don't think this can affect any non-OpenBSD builds, which of course aren't included in our CI.

**Comment by brad0** [comment]
Please backport to 2.5 and 2.4.

**Comment by lgritz** [comment]
I backported to 2.4 (in the dev-2.4 branch) and it will be part of the next tagged release scheduled for 1 May.

I'm not sure what you mean by "backport to 2.5." There is no official 2.5 release family yet; the current "master" branch is what will become 2.5 later this year.

**Comment by brad0** [comment]
> I'm not sure what you mean by "backport to 2.5." There is no official 2.5 release family yet; the current "master" branch is what will become 2.5 later this year.

I saw something that looked like tags towards a 2.5 release and wasn't sure so included it just in case.

**Comment by lgritz** [comment]
Yeah, I occasionally add "developer preview" tags to mark places that seem stable in the master branch, for people who need things that are only in master. But there's no support or backporting for those, just the occasional tag dropped to mark "I've used it in production here, seems ok."

**Pull request merged**
