### PR TITLE
Fixed a few compiler warnings issued by gcc 7.3.0-27ubuntu1~18.04

### PR DESCRIPTION
**Pull request by norru**
## Description

- fixes build failures of https://github.com/OpenImageIO/oiio.git on Ubuntu 18.04

## Tests

N/A

## Checklist:

- [X] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [N/A] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [N/A] I have updated the documentation, if applicable.
- [N/A] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [N/A] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
LGTM, thanks for the fixes.

**Comment by lgritz** [comment]
Whoa. I only realized after I hit the merge button that this is a PR against RB 1.2!

It may be in the tree, but I won't be releasing a tagged release patch to 1.2.  The current supported release is 1.8, which is mere days away from becoming obsolete as we release 2.0. 

I'll make sure these changes are propagated to master (though I suspect they have all long since been fixed in modern versions, which explains why I was surprised that they were still issues).

**Comment by lgritz** [comment]
In fact, I'm going to revert the fix. I don't want any activity on 1.2.

**Comment by lgritz** [comment]
If any of these are still issues in 1.8 or 2.0 (I bet they are not), then please let me know or submit a new PR against one of those branches.

**Comment by norru** [comment]
Hi @lgritz - Ditto! I was using the 1.2 branch because of the "official" build instructions in the README, tried to fix it - then shortly after realized that it was an obsolete one :)

I have successfully built with branch 1.8 - where similar warnings don't cause hard build failure.

**Pull request merged**
