### PR TITLE
Overhaul of metadata printing.

### PR DESCRIPTION
**Pull request by lgritz**
Airplane project from last weekend. This is for you, @danwexler 

* ImageSpec::to_xml() improvement: output contents of extra_attrib.
* ImageSpec::serialize() serializes the spec, as text or xml. Leaves
  room for other formats in the future. (JSON? YAML?)
* 'oiiotool -info:format=xml' prints metadata as xml

A bunch of refactoring to support this.

### CODE REVIEW

**Comment by lgritz** [comment]
I should point out, this doesn't change the formatting of the text output that oiiotool has always done, although it significantly refactors the code that does it. So nobody's output they are depending on should change. But if you want xml instead, this makes it possible.

**Comment by danwexler** [comment]
Compiled cleanly. Looks like oiiotool changes caused some unit test failures in my code. Debugging.

**Comment by lgritz** [comment]
How's this looking now, Dan? And please note I updated the patch since you wrote the "compiled cleanly" comment.

**Comment by danwexler** [comment]
LGTM! Passing all my unit tests. Thanks!

**Pull request merged**
