### PR TITLE
New ffmpeg core

### PR DESCRIPTION
**Pull request by dankamongmen**
## Description

As promised, I've rewritten the ffmpeg core for video support. I can successfully go through all my test videos with this code, including those which have caused the old implementation problems.

I'm not yet done -- seeking is ignored for the moment, we just do a linear traversal -- but I wanted to get some eyes on what I've done, and reassure you that I hadn't forgotten about this. Happy New Year.

## Tests

I'll do something here.

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ ] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
Definitely looking good! Let me know when you're comfortable with a merge (I guess when seeking works again?).

Don't forget to check the clang-format verification CI test, the bottom of the log for it will show you anything that isn't conformant with our style. Something it will not catch that I noticed you changed, though: we do customarily have 3 black lines between separate functions. It's not the end of the world, but if you are able to avoid deleting those lines from existing code, please do.

**Comment by dankamongmen** [comment]
> Definitely looking good! Let me know when you're comfortable with a merge (I guess when seeking works 
again?).

aye, when seeking works once more. it doesn't look like there's much in the way of video unit testing, unless i'm missing something. i can try to put a test or two in there; i've mostly been using oiiotool.
 
> Don't forget to check the clang-format verification CI test, the bottom of the log for it will show you anything that isn't conformant with our style. Something it will not catch that I noticed you changed, though: we do customarily have 3 black lines between separate functions. It's not the end of the world, but if you are able to avoid deleting those lines from existing code, please do.

got it.

**Comment by lgritz** [comment]
It's true, we don't have good unit testing of the ffmpeg code. It would be great to have some. I think the reason we lack it is just for lack of somebody taking the time to generate some test data that, you know, was not enormous (low res, not long videos), that adequately tested the feature set, and were not some video that we didn't have the rights to distribute.

If you had suitable tests (not huge, and test the right set of features, freely licensable or generated test images from you), it would be a very welcome addition.

If the test data are very small, you can just put it in testsuite/ffmpeg like the other format tests. If not fairly small (say, > a couple MB total) then the data files themselves should be checked into the oiio-images project, which is where we keep the larger test data that ordinary users probably don't want to download just to do a build. (You can see in testsuite/targa-tgautils/run.py, for example, how we reference things in that area.)

**Comment by dankamongmen** [comment]
I can easily put together some bespoke, license-clear sub-1M videos with kdenlive. I'll try to get to that. I'm hoping to have all this wrapped up by Friday, but no promises. Hack on!

**Comment by lgritz** [comment]
Outstanding, thanks! I think it would be a big asset to have that per-CI-run double check that a few of the most common video formats have not been inadvertently broken by anything else we've done. I think an adequate test would be to use oiiotool to extract a couple frames from the middle (oiiotool foo.avi -subimage 42 -o frame42.tif) and compare to a reference image.

**Comment by dankamongmen** [comment]
> Outstanding, thanks! I think it would be a big asset to have that per-CI-run double check that a few of the most common video formats have not been inadvertently broken by anything else we've done. I think an adequate test would be to use oiiotool to extract a couple frames from the middle (oiiotool foo.avi -subimage 42 -o frame42.tif) and compare to a reference image.

in my experience, this goes poorly with any non-lossless codec, due to new versions changing the output slightly (though this would be more on the encoder side than the decoder). i was going to start with just ensuring the expected number of frames can be extracted. a content test using a lossless format would probably be a good addition.

**Comment by lgritz** [comment]
Well, we don't have an encoder anyway (and if we did, we could still just keep one encoded version and not re-encode it for new versions). We experience the same thing for other formats -- libraw is the hardest, it's not uncommon for a new version to change the decoder and we have to support a growing number of reference outputs for the same input. It's not ideal, but I'd say that it's already par for the course for us.

**Comment by lgritz** [comment]
Hey, checking in on this.

Rereading this now, I'm not sure if we were waiting for you to make further code changes, or if we were only waiting for you to add a few tests (in which case we can always merge and add tests later).

@dankamongmen can you remind me where we are on this? Should I merge, or are there still rough edges here?

**Comment by lgritz** [comment]
Is this "I'm giving up", or "I'm about to submit a new PR that's a better full solution"?

**Comment by dankamongmen** [comment]
the latter, my friend! i was testing things out, and my whole method seems broken on windows for whatever reason. when i have it worked back out, i'll be putting a new one up here. https://github.com/dankamongmen/notcurses/issues/2355

**Comment by dankamongmen** [comment]
i'll be working on this today

**Pull request closed without merging**
