### PR TITLE
Impove ffmpeg backwards compatibility

### PR DESCRIPTION
**Pull request by sopvop**
Allows building with ancient ffmpeg on Centos6 and up to ffmpeg 3.0

Also api documentation state that av_free_packet should be called before
each av_read_frame call, unless packet is duped. Not doing that
can sometimes lead to segfaults. Better be safe.

Calling avcodec_close with null pointer caused segfaults on ancient ffmpeg.

### CODE REVIEW

**Comment by lgritz** [comment]
LGTM. Builds fine on all the Travis images as well as my home machine. I just need to double check that it builds properly with the systems I use at work, if so I will merge it on Monday.

**Comment by lgritz** [comment]
Merged into master.
Will merge into RB-1.6 in a couple days if nobody complains about trouble in master.

**Comment by lgritz** [comment]
Or do you even need it on RB-1.6?

**Comment by sopvop** [comment]
No, I'm on master

**Pull request closed without merging**
