### PR TITLE
pkgconfig OpenImageIO.pc was setting include dir one level too deep

### LINKED ISSUE #2868: [HELP] Do you have any feedback about this ? (Homebrew/pkg-config --cflags)
Hi all !

I wanted to have your feedback about this issue in homebrew with the openimageio package.
https://github.com/Homebrew/homebrew-core/issues/71360

You may spare me a lot of time of my free time if you do so :)

Thanks in advance.

### PR DESCRIPTION
**Pull request by lgritz**
Closes #2868

### CODE REVIEW

**Comment by lgritz** [comment]
@barbak Does this look right to you?

**Comment by barbak** [comment]
For my use case it's great. Hoping it's not breaking any projects.
I saw that other lib often double the include dirs:
```
% pkg-config --cflags IlmBase
-I/usr/local/Cellar/ilmbase/2.5.5/include -I/usr/local/Cellar/ilmbase/2.5.5/include/OpenEXR
```
Not sure it is a good practice though ...

**Comment by lgritz** [comment]
No, I think that's bad practice. I think all includes should look like `#include <OpenImageIO/foo.h>`, never just a raw `<foo.h>`, and so we definitely want this change. I'm willing to allow it to slightly break some people because it's definitely a bug as far as I'm concerned.

**Comment by lgritz** [comment]
I don't know how many people use the pkgconfig. I certainly don't, which is why I had not noticed this before. So maybe this will only fix people, and not break anybody.

**Comment by barbak** [comment]
This practice is fine with me. For the context, I was exhuming an old project that uses cmake and pkg-config. I don't think many projects use these kind of detection nowadays but it's always good to have this old pkg-config working correctly.
BTW, I think the problem is also in the OpenEXR library, https://github.com/AcademySoftwareFoundation/openexr/blob/master/cmake/OpenEXR.pc.in
I will contact them to see if they can fix that too !
Thanks again for your time.
Regards

**Pull request merged**
