### PR TITLE
Linking with OpenCV highgui component is not needed for 3.X and newer.

### PR DESCRIPTION
**Pull request by hobbes1069**
## Description

It is not necessary to link against the OpenCV highgui component in version 3.X and above as it has been split into 3 components.

## Checklist:

- [x ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ ] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [x ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x ] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
LGTM

**Comment by sambler** [comment]
This isn't completely right - libutil/paramlist_test needs to link with highgui.

```
FAILED: src/libutil/paramlist_test
...
src/libOpenImageIO/libOpenImageIO.so.1.9.3: undefined reference to 'cvCreateCameraCapture'
src/libOpenImageIO/libOpenImageIO.so.1.9.3: undefined reference to 'cvReleaseCapture'
src/libOpenImageIO/libOpenImageIO.so.1.9.3: undefined reference to 'cvQueryFrame'

```
So at least when building tests we still need to include highgui. That is if paramlist_test should be testing with camera capture.

**Comment by hobbes1069** [comment]
I'll wait for Larry to comment on whether camera capture is necessary. If so I'll relook and this. I know it's standard practice but I hate globbing libraries together and blindly linking them all or nothing with a target. -Wl,--as-needed can help with this but I don't like relying on it.

**Comment by lgritz** [comment]
No, paramlist_test definitely does not need any OpenCV functionality.

**Pull request merged**
