### PR TITLE
docs: Spruce up the main README and add "Building_the_docs"

### PR DESCRIPTION
**Pull request by lgritz**
For the upcoming DevDays, I wanted to spruce up our main README to make it easier to find info, and I wrote a new guide for how to locally build the documentation.

### CODE REVIEW

**Comment by lgritz** [comment]
@grdanny Would love your feedback on the "building the docs" docs, since you had to do that recently.

**Comment by lgritz** [comment]
You can see a preview of the new README here: https://github.com/lgritz/oiio/tree/lg-devdays

**Comment by lgritz** [comment]
Does this look like an improvement to people?

**Comment by grdanny** [comment]
It looks good to me.
Was able to follow it all on our work machines (using spk instead of pip).
I'm trying on my personal laptop too, but that is a bit more challenging because it's all windows so the main build has some issues.

I think you can go ahead and merge. I'll keep playing with it just so we are ready to answer some questions on dev day.
Your advice of trying to get all to build and manage your dependencies ahead of time is a good one as it does take a while to get all the different packages you need install and built.

**Pull request merged**
