### PR TITLE
ffmpeg: prefer O(N) march to O(1) broken seek #2688

### PR DESCRIPTION
**Pull request by dankamongmen**
## Description

Addresses #2688, in part. Some video formats include timestamps on each frame. Some include presentation indices on same. Some include neither. It is unsafe to rely on either of these two fields being set in an arbitrary `AVFrame`, as `read_frame()` currently does. For the same set of files that are broken in `read_frame()`, `seek()` with values other than 0 is similarly broken.

This PR purges any `seek()`ing, save to the beginning of the file (and some mysterious code in `open()` which seems to work well enough). Each `read_frame()` will now start at the beginning, count frames, and manually find the specified one (if it's available). This is slower than desirable for subsequent frames, but due to bugs, it has pretty much always worked this way (note in e.g. #2571 that I complain about very slow frame iteration using OIIO -- this was the cause). On the plus side, it actually loads the various frames of both #2688's test file, and the Notcurses test media.

This could probably be done better, but to do so, I'd need tear down `ffmpeginput.cpp` entirely and build it back up. Note that seeking is a best-effort kinda deal in FFmpeg. [This thread](http://lists.mplayerhq.hu/pipermail/libav-user/2013-September/005535.html) is informative.

Analysis was requested by good man @lgritz , so I performed some. IMHO this PR improves OIIO's video capabilities, but it by no means resolves all issues, and might have problems I haven't foreseen. Lasciate ogne speranza, voi ch'intrate -- buy the ticket, take the ride. I won't be offended if you don't merge it.

## Tests

I should [add a test], and didn't [add a test].

## Checklist:

- [X] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [X] If this is more extensive than a small change to existing code, I
  have previously submitted a Contributor License Agreement
  ([individual](../src/doc/CLA-INDIVIDUAL), and if there is any way my
  employers might think my programming belongs to them, then also
  [corporate](../src/doc/CLA-CORPORATE)).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [X] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
Thanks so much!

I would much rather it be *correct* than be *fast*. O(n) for out-of-order seek is reasonable, as long as sequential frame access (which is the usual case) is fast. 

In general, OIIO does not pretend to be an API for movie files (for example, it is totally ignorant of audio or any proper control of typical video codec features). It just so happens that we can support basic functionality when your only use case is treating it like a multi-image file (with many many images) for basic operations like extracting a representative frame or non-realtime converting the video into individual frames in a different still image format.

I'll do a couple basic tests (single frame extraction and just eyeball it to see if it's plausible) on a few videos I have on hand, and if it works, I will do the merge.

I really appreciate your taking the time to look into this.

**Comment by lgritz** [comment]
Spot check looks good. Merging. Thanks, Nick!

**Comment by lgritz** [comment]
Wait, hold the presses!

I just reread your comments, and if I now understand, you are saying that EVERY frame read, even "next frame", will start at the beginning?

This would imply that the use case of extracting a single frame would be O(n) of the frame number you want, but that a script that looped over all the whole video would be O(n^2) on the number of frames.

I did some spot checks on movie files I have lying around, doing the single-frame extraction at frames 1, 10, 100, 1000, 10000 (`oiiotool movie.mp4 -subimage n -o out.jpg`), and did see approximately linear time. It was very fast for early frames, but painfully slow for late frames (3 mins on my laptop to extract frame 10000). For the common use case of looping over the video to extract all the individual frames (e.g., `oiiotool movie.mp4 -sisplit -o:all=1 frame.%04d.tif`), which I calculate would be over 4 hours for a 10000 frame movie, which is unusable.

So I'm not ready to merge this yet, I think the downside is very bad. (Note that although we have recently noticed particular files weirdo that have problems with the janky code we have, mostly people have been using it without complaint, so let's not throw the baby out with the bathwater.)

It seems to me that it should be fairly straightforward to change this PR as it stands to not seek EVERY time, but in fact to notice the common case that it's being asked to seek to the very next frame, and it just reads it rather than reseeking. Am I reading the code right that this should be easy? Because if that's feasible, then I think this is salvageable. If single sequential read of an open file is O(1), even if random access seek is O(n), I think we can live with that for now (but with the goal of an arbitrary seek eventually being closer to O(1), as it clearly can be from the observed behavior of video players.

**Comment by dankamongmen** [comment]
> Wait, hold the presses!
> 
> I just reread your comments, and if I now understand, you are saying that EVERY frame read, even "next frame", will start at the beginning?
> 
> This would imply that the use case of extracting a single frame would be O(n) of the frame number you want, but that a script that looped over all the whole video would be O(n^2) on the number of frames.
> 
> I did some spot checks on movie files I have lying around, doing the single-frame extraction at frames 1, 10, 100, 1000, 10000 (`oiiotool movie.mp4 -subimage n -o out.jpg`), and did see approximately linear time. It was very fast for early frames, but painfully slow for late frames (3 mins on my laptop to extract frame 10000). For the common use case of looping over the video to extract all the individual frames (e.g., `oiiotool movie.mp4 -sisplit -o:all=1 frame.%04d.tif`), which I calculate would be over 4 hours for a 10000 frame movie, which is unusable.
> 
> So I'm not ready to merge this yet, I think the downside is very bad. (Note that although we have recently noticed particular files weirdo that have problems with the janky code we have, mostly people have been using it without complaint, so let's not throw the baby out with the bathwater.)
> 
> It seems to me that it should be fairly straightforward to change this PR as it stands to not seek EVERY time, but in fact to notice the common case that it's being asked to seek to the very next frame, and it just reads it rather than reseeking. Am I reading the code right that this should be easy? Because if that's feasible, then I think this is salvageable. If single sequential read of an open file is O(1), even if random access seek is O(n), I think we can live with that for now (but with the goal of an arbitrary seek eventually being closer to O(1), as it clearly can be from the observed behavior of video players.

Yes, everything you describe here is accurate, and I had reached the same conclusions. I wanted to make sure the overall approach was going to fly. Yes, the O(N) is per-frame, so O(N^2) seeks for the entire video with this PR (though as I note, the broken timestamp-based sync meant that you were pretty much doing exactly this much work for the vast majority of formats anyway -- remember me complaining about "man oiio is slow on videos" a few months ago?).

I'm happy to speed this up as proposed, but I doubt I can get to it before this weekend. IMHO, this is an improvement (only due to the current performance being unintentionally poor for most files).

Now, if you'd like, what I could do for you is a true legit-by-my-standards-and-knowledge rewrite, dumping what's there and going purely off frame numbers, keeping the necessary state to do it perfectly (so far as I'm aware). It would probably be a full day's work, but in the end I'd be much more confident in it than what we would have otherwise. More churn, of course. Another benefit is that I'll have basically the same loop in Notcurses, which I test quite extensively around FFmpeg, so fixes could cross-pollinate.

So I can go either way, but I can't do either in the very short term -- I'd have an opening early next week, I think.

You're of course welcome to augment this PR however you might like to do so.

Does that seem reasonable? I'm happy to pitch in on such an august project, and even to become the "maintainer" of your ffmpeg code if you'd like. Let me know your thoughts, and you're welcome for the patch -- it's always a pleasure to work with you.

**Comment by lgritz** [comment]
I'm inclined to try myself making just the most minor tweak to this PR to see if I can make the "get the very next frame" case be O(1) rather than O(n). If it's an easy change that immediately and obviously works, I'll amend the PR and merge it, even if it's destined for a larger overhaul later.

I happily accept your offer to rewrite it the "right" way and to be an ongoing maintainer of the ffmpeg-related code! It's such a generous (and truly needed) offer that I'm in no position to quibble about timeline. Like I said, for the most part, people are using this code on their typical use cases with only the occasional complaint about edge cases (maybe we get lucky that the few formats that the current code works well for are the ones our users frequently encounter?), so there is no dire emergency we are addressing. I think if you are talking about days or even weeks (versus many months) before you can get to this, it's all good.

**Comment by lgritz** [comment]
Never mind what I said about taking a stab at it myself, I don't know enough about the ffmpeg API to know what I'm doing. I'm sure that just waiting for you to fix this the right way is the best way to proceed. At least that's not making it any worse than it already is.

**Comment by dankamongmen** [comment]
to do what you want, it ought be sufficient to:

 - reintroduce the "last_seek" class member
 - wrap the seek(0) in read_frame with a check as to whether
      last_seek + 1 is equivalent to the input frame
 - to really go 💯, initialize last_seek to -1 to avoid an
      unnecessary seek on the first iteration

this will remain as correct as it would otherwise be, and do a
subsequent frame load in O(1) rather than O(N).

looking forward to help improve OIIO =]

**Comment by lgritz** [comment]
Not that there's any rush, but just checking in on this...

**Comment by dankamongmen** [comment]
> Not that there's any rush, but just checking in on this...

hey hey hey! i intend to tackle this over the thanksgiving break (the weekend following 2020-11-26).

**Comment by dankamongmen** [comment]
Oh! Did this fix never get checked in? I thought it had as a stopgap.

**Comment by lgritz** [comment]
I think that we held off on committing this because it's a big performance hit, to fix a correctness issue only on some file configurations that in practice few people had complained about. So we were thinking that waiting a little longer for the full fix was better than totally borking the performance for people for whom it had been working fine all along.

Yeah, no worries about the delay, we would be very happy to get this really fixed well, on whatever timetable you have. I just didn't want it to go forgotten.

**Comment by dankamongmen** [comment]
Alright, I started in on this, and think I can probably have it done today. A few questions:

* there's a ton of `#define` and `#ifdef` clutter for ancient versions of FFMpeg. 4.0 was released 2018-04-20. I don't have means to test against older versions. How married to these are we?
* `FFmpegInput::open()` has an extensive map of FFmpeg types to OIIO types. Do we intend to keep this up-to-date, or ought I normalize to some OIIO type?
* I'm guessing we pretty much have to register extensions, and can't just get passed media on a try-it-out basis?

**Comment by lgritz** [comment]
> there's a ton of #define and #ifdef clutter for ancient versions of FFMpeg. 4.0 was released 2018-04-20. I don't have means to test against older versions. How married to these are we?

If we change the ffmpeg minimum, then these changes can only go in master (future OIIO 2.3) and can't be backported to the OIIO 2.2 release family (release branches promise continued support for dependency versions).

Personally, I'm ok with raising the minimum (and having the fixes in master only) if it makes this work significantly easier for you. But if you think (as a user of it yourself) that it's important that all your improvements make it to a release branch and into the various distributions right away, then you'll need to keep it working for the current set of supported ffmpeg set of releases.

Upon checking, I'm linking against ffmpeg 3.4 at work. But coincidentally, I saw a ticket just this past week indicating that we're in the process of setting up a 4.x build, so I *think* I'll be able to safely switch to that after these changes are merged.

Browsing ffmpeginput.cpp, it looks to me that (almost?) all of the potential simplification would be from raising the minimum to ffmpeg 3.1. So I would suggest that as a potential compromise that would minimize the number of users who are inconvenienced, while still removing most of the clutter. Unless to get this all right you truly need 4.x features, in which case I defer to your judgment.

> FFmpegInput::open() has an extensive map of FFmpeg types to OIIO types. Do we intend to keep this up-to-date, or ought I normalize to some OIIO type?

I only see a small number of OIIO types: { uint8, uint16, float }, but in some cases { 1, 3, or 4 } channels. Then a whole lot of different ways things could be in the FFmpeg files, which all map onto those small number of choices.

I don't think we can make the OIIO side smaller -- I don't want to lose precision for apps that need it (for example, forcing everything to be returned as uint8 even if it were uint16 or float in the file), nor to force data expansion unnecessarily (like making even a uint8 ffmpeg appear to OIIO apps as if it were full float data).

Or am I misuderstanding the issue?


> I'm guessing we pretty much have to register extensions, and can't just get passed media on a try-it-out basis?

I'm not sure I know what you mean by this.

**Pull request closed without merging**
