### PR TITLE
More robust test for gamma value in cineon files.

### PR DESCRIPTION
**Pull request by lgritz**
Pointed out in #154 by Frédéric Devernay.

### CODE REVIEW

**Comment by lgritz** [comment]
@devernay

**Comment by devernay** [comment]
ok, except I still don't understand if a "reasonable" gamma value (not like oiio extracts from Nuke-produced cineons, see #1463) means that the cineon response curve is a gamma curve, or if it's the Cineon (log) curve followed by gamma...

**Comment by lgritz** [comment]
Updated this PR with a new strategy: just label the color space "KodakLog" and forget about the gamma. This seems to be fine and corresponds to the real-world state of Cineon files, as far as we know. We can always revisit if people are encountering Cineon files that are not log encoded.

**Comment by lgritz** [comment]
Fixes #1463

**Comment by lgritz** [comment]
Does this seem like a reasonable approach for now?

**Comment by devernay** [comment]
yes, great!
I would also change CINEON_SET_ATTRIB_COORDS to check for 0.,0 so that the Kodak Digital LAD reads correctly.
neither the white point nor chromaticities can have (0,0) coordinates anyway
```
#define CINEON_SET_ATTRIB_COORDS(x)     m_cin.header.x (floats);            \
                                        if (!isinf (floats[0])              \
                                            && !isinf (floats[1]) && !(floats[0] == 0. && floats[1] == 0.))          \
                                            m_spec.attribute ("cineon:" #x, \
                                                TypeDesc (TypeDesc::FLOAT,  \
                                                2), &floats[0])
```

**Comment by lgritz** [comment]
I made this change, too. As soon as the CI tests are done, I'll merge this if it's ok.

Is master good for you on this, or do you want it backported to the release branch right away?

**Comment by devernay** [comment]
master is OK, as I'm hacking it on my side anyway: https://github.com/MrKepzie/openfx-io/blob/master/OIIO/ReadOIIO.cpp#L1715

**Pull request merged**
