### PR TITLE
[raw] update exif orientation with raw flip if user flip is set

### PR DESCRIPTION
**Pull request by servantftechnicolor**
If raw:user_flip is set, the flip field of the raw input is replaced with the value of raw:user_flip and the original flip value is lost.

If raw:user_flip is set to 1, we can consider the user wanted to disable the buffer rotation.

We may want to display it correctly anyway. This PR proposes to store the original flip value inside the exif orientation code.

### CODE REVIEW

**Comment by fabiencastan** [comment]
Fix https://github.com/OpenImageIO/oiio/issues/3574

**Review by lgritz — CHANGES_REQUESTED** [review]
The changes LGTM. 

Please look at the results of the clang-format CI test and adjust formatting as it advises.

Don't worry about the other failed test -- it seems to have failed while setting up dependencies, and is unrelated to your changes. Probably a momentary error in availability of a server that is needed to download deps.

**Comment by servantftechnicolor** [comment]
The Clang check fail but i don't see anything to do in the log ...

**Comment by lgritz** [comment]
If you click on the "details" button for that test, at the bottom of the log in the build section, you'll see a diff of the clang-formatted version and what you submitted.

Looks like there is one line with some extra whitespace. Don't worry about it, I'll merge this and then fix it separately. I don't want to make more work for you than is necessary, I really appreciate your submitting this fix.

**Comment by fabiencastan** [comment]
Thanks

**Pull request merged**
